# 服务器 配置
server:
  # 服务器 端口
  port: 80
#
# Spring Boot 配置
spring:
  # Thymeleaf 配置
  thymeleaf:
    # 是否启用模板缓存。
    cache: false
#
# 阿里云 配置
aliyun:
  # 阿里云 OSS 配置
  oss:
    access-key-id:
    access-key-secret:
    # EndPoint（地域节点）
    endpoint:
    # Bucket 域名（不含EndPoint（地域节点））
    bucket:
    # 上传地址前缀
    dir:
    # 回调服务器地址
    callback-url:
#
# 日志 配置
logging:
  level:
    web: debug
    cn.com.xuxiaowei: debug